use customer_behaviour;

select * from shopping_data;

-- Q1. What is the total revenue generated by male VS female customer?

SELECT gender, SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id,purchase_amount
FROM shopping_data
WHERE discount_applied = 'Yes' AND purchase_amount > (
                           SELECT AVG(purchase_amount) FROM shopping_data);

-- Q3. Which are the top five products with the highest average review rating? 

select item_purchased, avg(review_rating) from shopping_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average purchase amount between Standard and Express shipping.

select shipping_type, avg(purchase_amount) from shopping_data
where shipping_type in ('standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total spend between subscribers and non subscribers. 

SELECT 
subscription_status,
    AVG(purchase_amount_usd) AS average_spend,
    SUM(purchase_amount_usd) AS total_revenue,
    COUNT(*) AS total_customers
FROM shopping_data
GROUP BY subscription_status;

-- Q6. Which five products have the highest percentage of purchases with discounts applied? 

SELECT 
    item_purchased,
    (SUM(discount_applied = 'Yes') * 100 / COUNT(*)) AS discount_percentage
FROM
    shopping_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into new, returning, and loyal based on their total number of previous purchases and show the count of each segment. 

SELECT 
    CASE
        WHEN previous_purchases <= 10 THEN 'New'
        WHEN previous_purchases <= 25 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM shopping_data
GROUP BY customer_segment;

-- Q8. What are the top 3 purchased products within each category? 

SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER(
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM shopping_data
    GROUP BY category, item_purchased
) x
WHERE rn <= 3;

-- Q9. Are customers who are repeat buyers (More than five previous purchases) Virtual likely to subscribe? 

SELECT 
    subscription_status,
    COUNT(*) AS total_customers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue mission of each age group? 

select age_group, sum(purchase_amount) as total_revenue from shopping_data
group by age_group
order by total_revenue desc;